update with doc template
Hyperledger-TWGC/java-gm pull request #26
Opened 2020-11-15 14:27 UTC by SamYuan1990

update with doc template

Signed-off-by: SamYuan1990 <yy19902439@126.com>

2020-11-15 14:30 UTC, SamYuan1990 commented on README.md
> +| PEM格式导入 | `私钥/公钥/CSR/证书` |
这里好像尚未支持csr/证书格式啊。

2020-11-15 14:47 UTC, davidkhala commented on README.md
> +| PEM格式导入 | `私钥/公钥/CSR/证书` |
如果还没支持的话，就不写相关支持就行，比如写成`私钥、公钥`

2020-11-16 15:44 UTC, davidkhala requested changes
Change accordingly

2020-11-17 16:23 UTC, SamYuan1990 commented
updated.

2020-11-18 01:38 UTC, davidkhala commented on README.md
> -基于BouncyCastle实现国密算法SM2、SM3、SM4的操作类，并验证与其他语言（NodeJS、Go）实现的国密库的互操作性。
这句话作为项目基本介绍应该不需要删掉

2020-11-18 01:48 UTC, davidkhala commented on README.md
> +# java-gm [![Build Status](https://dev.azure.com/Hyperledger/TWGC/_apis/build/status/Hyperledger-TWGC.java-gm?branchName=master)](https://dev.azure.com/Hyperledger/TWGC/_build/latest?definitionId=129
这个badge怎么移动到上面去了？

2020-11-18 01:50 UTC, SamYuan1990 commented on README.md
> +# java-gm [![Build Status](https://dev.azure.com/Hyperledger/TWGC/_apis/build/status/Hyperledger-TWGC.java-gm?branchName=master)](https://dev.azure.com/Hyperledger/TWGC/_build/latest?definitionId=129
![image](https://user-images.githubusercontent.com/7820992/99472386-724c7500-2983-11eb-97ca-4e7b383f02b3.png)

2020-11-18 01:50 UTC, SamYuan1990 commented on README.md
> +# java-gm [![Build Status](https://dev.azure.com/Hyperledger/TWGC/_apis/build/status/Hyperledger-TWGC.java-gm?branchName=master)](https://dev.azure.com/Hyperledger/TWGC/_build/latest?definitionId=129
![image](https://user-images.githubusercontent.com/7820992/99472410-7ed0cd80-2983-11eb-9440-c15b1490fa3b.png)

2020-11-18 01:51 UTC, SamYuan1990 commented on README.md
> +# java-gm [![Build Status](https://dev.azure.com/Hyperledger/TWGC/_apis/build/status/Hyperledger-TWGC.java-gm?branchName=master)](https://dev.azure.com/Hyperledger/TWGC/_build/latest?definitionId=129
我觉的上去好看一些

2020-11-18 01:56 UTC, SamYuan1990 commented on README.md
> +# java-gm [![Build Status](https://dev.azure.com/Hyperledger/TWGC/_apis/build/status/Hyperledger-TWGC.java-gm?branchName=master)](https://dev.azure.com/Hyperledger/TWGC/_build/latest?definitionId=129
moved back

2020-11-18 14:35 UTC, davidkhala commented on README.md
> +# java-gm [![Build Status](https://dev.azure.com/Hyperledger/TWGC/_apis/build/status/Hyperledger-TWGC.java-gm?branchName=master)](https://dev.azure.com/Hyperledger/TWGC/_build/latest?definitionId=129
主要是Github实装的效果和一般IDE里面的markdown解释器不太一样的

2020-11-18 14:36 UTC, davidkhala approved these changes
LGTM

2020-11-18 14:36 UTC, merged