fix for #25
Hyperledger-TWGC/java-gm pull request #27
Opened 2020-11-16 03:41 UTC by SamYuan1990

adding support for derive pub from private

Signed-off-by: SamYuan1990 <yy19902439@126.com>

2020-11-16 08:07 UTC, davidkhala commented on src/test/java/SM2UtilTest.java
> +        Assert.assertNull(t);
I think that last null assert is not required.

2020-11-16 08:20 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +        Assert.assertNull(t);
right, updated.

2020-11-16 08:29 UTC, czdsdo commented on src/test/java/SM2UtilTest.java
> +        Assert.assertNull(t);
No problem.I think it can derive public key from private key.

2020-11-16 08:34 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +        Assert.assertNull(t);
@czdsdo , the point is, the function been tested here without any exception throw, so we don't need catch exception equals to null.

the try catch is for key load function, as a part of init steps. and if there any mistakes, error also been captured.
therefor, no need duplication for null assert here.

2020-11-16 15:39 UTC, davidkhala commented on src/test/java/SM2UtilTest.java
> +        Assert.assertNull(t);
同理

2020-11-16 15:40 UTC, davidkhala commented on src/test/java/SM2UtilTest.java
> +            Assert.assertEquals("key should be same", pubKey, deriveKey);
Assert断言如果发生了不满足的情况，会作为异常抛出么？如果是的话，那么这里写法就应该在测试入口允许丢出异常

2020-11-16 15:41 UTC, davidkhala requested changes
-

2020-11-16 15:42 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +        Assert.assertNull(t);
不同理吧。
```
    public static boolean verify(Signature signature, PublicKey publicKey, byte[] message, byte[] sigBytes) throws InvalidKeyException, SignatureException {
```
这里着实要避免被测函数抛出异常的现象啊。

2020-11-16 15:43 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +            Assert.assertEquals("key should be same", pubKey, deriveKey);
Assert断言如果发生了不满足的情况，那么gradle test，或者我们说unit test会报错。
并不会作为异常抛出。

2020-11-16 15:47 UTC, davidkhala commented on src/test/java/SM2UtilTest.java
> +    public void getPublic() {
Java 单元测试入口允许丢出异常么？这是一个单纯的问题，并非建议

2020-11-16 16:17 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +    public void getPublic() {
我抽空查查看吧。我记得一般都是测试异常才抓。
https://blog.csdn.net/Dream_Weave/article/details/83860631

2020-11-16 16:18 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +    public void getPublic() {
而相对的，我觉得我们目前没写异常的测试case，所以要抓没异常。。。

2020-11-16 16:50 UTC, davidkhala commented on src/test/java/SM2UtilTest.java
> +            t = e;
这个位置其实不需要为t赋值，也不需要接下来的assertNull，本质上这里直接hardcode一个assert 失败即刻

2020-11-16 16:50 UTC, davidkhala commented on src/test/java/SM2UtilTest.java
>              t = e;
这个位置其实不需要为t赋值，也不需要接下来的assertNull，本质上这里直接hardcode一个assert 失败即刻

2020-11-16 16:50 UTC, davidkhala commented on src/test/java/SM2UtilTest.java
>              t = e;
这个位置其实不需要为t赋值，也不需要接下来的assertNull，本质上这里直接hardcode一个assert 失败即可

2020-11-16 17:03 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
>              t = e;
k

2020-11-17 15:12 UTC, davidkhala approved these changes
LGTM

2020-11-17 15:12 UTC, merged