增加sm4算法java（bouncycastle）与go（tjfoc）的相互校验
Hyperledger-TWGC/java-gm pull request #34
Opened 2020-12-05 04:40 UTC by xiaohui249

Signed-off-by: xiaohui249 <xiaohui_1123@126.com>

2020-12-05 10:16 UTC, davidkhala commented on .gitignore
> +/gradle/
@SamYuan1990 大家讨论下这个gradle文件夹需不需要进代码库吧

2020-12-05 10:19 UTC, SamYuan1990 commented on .gitignore
> +/gradle/
进，只要我们还用azp做ci就不得不进。
这个是azp不完善的地方。

2020-12-05 10:25 UTC, SamYuan1990 requested changes

2020-12-05 10:25 UTC, SamYuan1990 commented on src/test/java/SM4UtilTest.java
> +import org.bc.pqc.math.linearalgebra.ByteUtils;
missing  class？

2020-12-05 10:25 UTC, SamYuan1990 commented on src/test/java/SM4UtilTest.java
> -    static String message = RandomStringUtils.random(randomData);
之前我们对于非互交互的测试用例使用了128位随机字符做测试。。。为啥这部分要改回去？

2020-12-05 10:25 UTC, SamYuan1990 commented on src/test/java/SM4UtilTest.java
> +import org.bc.pqc.math.linearalgebra.ByteUtils;
你这个类不在gradle的jar dep里啊。

2020-12-06 05:19 UTC, xiaohui249 commented on src/test/java/SM4UtilTest.java
> +import org.bc.pqc.math.linearalgebra.ByteUtils;
ByteUtils这个类是在java8的扩展库gmjce.jar里面，我本地SM4UtilTest的方法都是测试成功，只是整个工程build失败，失败原因在SM2UtilTest.keyPairWithPasswd(SM2UtilTest.java:139)，报错：“java.lang.AssertionError: Exception happened”。
至于SM4这里没有使用随机数，是因为没有完全互操作，go和java两边需要手动进行交互验证，随机的话无法保证两边需要加解密的内容一致。

2020-12-06 05:20 UTC, xiaohui249 commented on src/test/java/SM4UtilTest.java
> -    static String message = RandomStringUtils.random(randomData);
SM4这里没有使用随机数，是因为没有完全互操作，go和java两边需要手动进行交互验证，随机的话无法保证两边需要加解密的内容一致。

2020-12-06 05:44 UTC, xiaohui249 commented on src/test/java/SM4UtilTest.java
> +import org.bc.pqc.math.linearalgebra.ByteUtils;
ByteUtils这个类我用bc库中进行了替换，ci通过了

2020-12-06 06:48 UTC, SamYuan1990 commented on src/test/java/SM4UtilTest.java
> +import org.bc.pqc.math.linearalgebra.ByteUtils;
行吧，这个missing class的问题解决了。
我很好奇，你本地的ide没检测出这个类丢失。。。不过我们目前解决了就好。

2020-12-06 06:52 UTC, SamYuan1990 commented on src/test/java/SM4UtilTest.java
> +    public void sm4Interaction4Decrypt() throws Exception {
我不理解的就在这里了。
这两个新加的测试才是互操作的。那么上边的测试都是java-gm库自己的ut。我没有必要和golang保持一致啊。
反之，那么为什么只有这两个测试名称里有`Interaction`？

2020-12-06 06:54 UTC, SamYuan1990 commented on .gitignore
> +/gradle/
https://docs.microsoft.com/zh-cn/azure/devops/pipelines/tasks/build/gradle?view=azure-devops#how-do-i-generate-a-wrapper-from-my-gradle-project
@davidkhala

2020-12-13 06:36 UTC, xiaohui249 commented
@SamYuan1990 SM4UtilTest中的前4个单元测试（非NoPadding模式）已经改为随机生成字符串。

2021-01-08 12:26 UTC, SamYuan1990 approved these changes

2021-01-08 12:29 UTC, merged