Update SM2Util.java
Hyperledger-TWGC/java-gm pull request #46
Opened 2021-01-18 03:22 UTC by EdgarLQS

add getX509Certificate
增加读取X509证书的方法到SM2Util.java中

2021-01-18 05:01 UTC, SamYuan1990 commented
@EdgarLQS , 
感谢贡献。
请为这个pr添加测试案例并通过ci检测。
请通过`git commit -s`来提交comments。因为我们开启了了DCO检测。
在这之前请先把这pr转为draft。这样，当这个pr状态从draft转换为open的时候我们（reviewer）就可以知道这个pr完成了。
谢谢。

2021-01-18 14:21 UTC, SamYuan1990 commented
我先转化为Draft了，通过了CI之后请点击Ready for review。

2021-01-18 14:24 UTC, EdgarLQS commented
好的，第一次弄，比较尴尬。。。

2021-01-19 03:54 UTC, SamYuan1990 requested changes

2021-01-19 03:54 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +        String strCertificate = "-----BEGIN CERTIFICATE-----\n" +
我希望我们不仅仅是一个读文件的pr，而是包括写在内的一个全功能展示。

2021-01-19 03:54 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +        Assert.assertEquals("SM3WITHSM2", x509Certificatefrombyte.getSigAlgName());
我觉得我们最好增加一些其他的属性在这个测试里。

2021-01-19 03:54 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +        String strCertificate = "-----BEGIN CERTIFICATE-----\n" +
因此建议动态生成证书。

2021-01-19 03:54 UTC, SamYuan1990 commented on src/main/java/SM2Util.java
> +    public static X509Certificate getX509Certificate(String certFilePath) throws IOException, CertificateException,
我是在思考有没有必要。
即我们是提供一个核心函数`X509Certificate getX509Certificate(InputStream is)` 还是我们要提供各种格式的函数？

2021-01-19 03:54 UTC, SamYuan1990 commented
另外，建议添加线程安全性测试。

2021-01-31 06:54 UTC, SamYuan1990 requested changes

2021-01-31 06:54 UTC, SamYuan1990 commented on src/main/java/SM2Util.java
> +        ContentSigner signerBuilder = new JcaContentSignerBuilder("SM3WITHSM2")
use const SM3SM2_VALUE instead, pls.

2021-01-31 06:54 UTC, SamYuan1990 commented on src/main/java/SM2Util.java
> +                .setProvider(BouncyCastleProvider.PROVIDER_NAME).build(priKey);
do we need set Provider agagin?

2021-01-31 06:54 UTC, SamYuan1990 commented on src/main/java/SM2Util.java
> +    public static PKCS10CertificationRequest generateCSR(X500Name subject, PublicKey pubKey, PrivateKey priKey) throws OperatorCreationException {
generateCSR ... we have a same name method right? do we need refactor replace?

2021-01-31 06:54 UTC, SamYuan1990 commented on src/main/java/SM2Util.java
> +    public static X509Certificate getX509Certificate(String certFilePath) throws IOException, CertificateException,
please use io stream instead of file name.

2021-01-31 06:54 UTC, SamYuan1990 commented on src/main/java/cert/SM2X509CertMaker.java
> +    public static X500Name buildRootCADN() {
`O = org.zz` 这是用户手工输入的，不要hard code。

2021-01-31 06:54 UTC, SamYuan1990 commented on src/main/java/cert/RandomSNAllocator.java
> +public class RandomSNAllocator implements CertSNAllocator {
这个类只是为了生成随机数么？ @czdsdo , @guijunchen , 劳烦确认下国密的x509证书是否需要这样特殊的随机数逻辑？

2021-01-31 06:54 UTC, SamYuan1990 commented on src/main/java/cert/SM2X509CertMaker.java
> +    public static final String SIGN_ALGO_SM3WITHSM2 = "SM3WITHSM2";
常量。。。重构一下？

2021-01-31 06:54 UTC, SamYuan1990 commented on src/main/java/cert/SM2X509CertMaker.java
> +    private JcaContentSignerBuilder makeContentSignerBuilder(PublicKey issPub) throws Exception {
这个代码逻辑重复了？

2021-01-31 06:54 UTC, SamYuan1990 commented on src/main/java/cert/SM2X509CertMaker.java
> +    private X509Certificate makeCertificate(CertLevel certLevel, Integer pathLenConstrain,
建议把这个函数拆开。就是把准备阶段和生成阶段，还有签名阶段分开。
避免写一个超长的函数，便于阅读。

2021-01-31 06:54 UTC, SamYuan1990 commented on src/main/java/cert/SM2X509CertMaker.java
> +        RDN[] rdns = subject.getRDNs();
我不确定这里有些变量是不是可以通过依赖倒置的思路作为输入参数。

2021-01-31 06:54 UTC, SamYuan1990 commented on src/main/java/cert/SM2X509CertMaker.java
> +        switch (certLevel) {
```
                if (issuerDN.equals(subject)) {
                    selfSignedEECert = true;
                    subject = issuerDN;
                } else {
switch ... {
throw different kind of exception.
} 
}
```

2021-01-31 06:54 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +    @Test
证书生成移动至Before函数，已备互操作库的调用。
另外： 测试请写为(伪代码)
```
@before
// 准备一些数据
// 生成证书

@test
// 读取证书
// 确认证书内的内容 符合在before中的数据
```

2021-02-04 10:54 UTC, EdgarLQS commented on src/test/java/SM2UtilTest.java
> +    @Test
证书生成已移到before里面，generateCSR 保留了一个（之前的），makeCertificate（）进行了一定的简化（线程安全测试未做）

2021-02-14 15:23 UTC, davidkhala commented
@EdgarLQS 这个PR最近还在做么？

2021-02-15 11:57 UTC, EdgarLQS commented
最近没有做了，还有需求的话等下周上班了可以继续看下





------------------ Original ------------------
From: David Liu <notifications@github.com&gt;
Date: Sun,Feb 14,2021 11:24 PM
To: Hyperledger-TWGC/java-gm <java-gm@noreply.github.com&gt;
Cc: EdgarLQS <751232541@qq.com&gt;, Mention <mention@noreply.github.com&gt;
Subject: Re: [Hyperledger-TWGC/java-gm] Update SM2Util.java (#46)





 
@EdgarLQS 这个PR最近还在做么？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-07 15:16 UTC, davidkhala commented
@EdgarLQS 还有比较多的git commit结构性问题没解决，先转化为draft了，如果你觉得做好了，请转为Open

2021-04-08 00:42 UTC, EdgarLQS commented
> 
> 
> @EdgarLQS 还有比较多的git commit结构性问题没解决，先转化为draft了，如果你觉得做好了，请转为Open

好的，现在是冲突了，本地跑 gradle clean build 没什么问题

2021-04-08 01:44 UTC, davidkhala commented
@EdgarLQS 那就好，是跟sam的部分冲突了么？

2021-04-14 14:50 UTC, closed without merging