使用对象通用池来管理Cipher对象，优化性能同时避免线程安全
Hyperledger-TWGC/java-gm pull request #47
Opened 2021-01-22 02:05 UTC by xiaohui249

Signed-off-by: xiaohui249 <xiaohui_1123@126.com>

2021-01-22 02:09 UTC, xiaohui249 commented
@SamYuan1990 @davidkhala 本次pr只针对SM4_CBC_PKCS7Padding的Cipher进行了池化，这样既解决了线程安全问题，同时也解决了Synchronized造成的同步阻塞问题，提高并发性能。

2021-01-22 02:38 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +        CipherPoolHolder.getPool(sm4ModeAndPaddingEnum).returnObject(obj);
if exception throws, the borrowed obj will not back into pool

2021-01-22 02:42 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/pool/CBC7PaddingCipher.java
> +        cipher = Cipher.getInstance(SM4ModeAndPaddingEnum.SM4_CBC_PKCS7Padding.getName(), BouncyCastleProvider.PROVIDER_NAME);
SM4_ECB_NoPadding("SM4/ECB/NoPadding"),
    SM4_ECB_PKCS5Padding("SM4/ECB/PKCS5Padding"),
    SM4_ECB_PKCS7Padding("SM4/ECB/PKCS7Padding"),
    SM4_CBC_NoPadding("SM4/CBC/NoPadding"),
    SM4_CBC_PKCS5Padding("SM4/CBC/PKCS5Padding"),
    SM4_CBC_PKCS7Padding("SM4/CBC/PKCS7Padding");

why only for SM4_CBC_PKCS7Padding here?

2021-01-22 02:42 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/pool/CipherPoolHolder.java
> +        poolMap.put(SM4ModeAndPaddingEnum.SM4_CBC_PKCS7Padding.getName(), new CBC7PaddingCipherPool(5, 10));
SM4_CBC_PKCS7Padding only?

2021-01-22 02:43 UTC, SamYuan1990 commented on src/test/java/SM4UtilTest.java
> +//                {content16, SM4ModeAndPaddingEnum.SM4_ECB_NoPadding, false},
why removed?

2021-01-22 02:44 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +        Cipher cipher = ((ICipher) obj).getCipher();
```
Cipher cipher = ((Cipher) obj)
```
???

2021-01-22 02:45 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +        if (ivParameterSpec == null) {
why not get obj from pool here?

2021-01-22 02:46 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +        if (ivParameterSpec == null) {
how about we get cipher from pool here?

2021-02-12 13:22 UTC, SamYuan1990 commented
@xiaohui249 ， please squash commits when completed.

2021-02-14 11:02 UTC, xiaohui249 commented
> @xiaohui249 ， please squash commits when completed.

done

2021-02-14 11:39 UTC, SamYuan1990 requested changes

2021-02-14 11:39 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +            System.out.println("加密Cipher:" + cipher);
remove this system.out.println here.

2021-02-14 11:39 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +            SecretKeySpec sm4Key = new SecretKeySpec(key, ALGORITHM_NAME);
why not 
```
public byte[] encrypt(byte[] input, SecretKeySpec sm4Key, SM4ModeAndPaddingEnum sm4ModeAndPaddingEnum, byte[] iv) throws Exception
```

2021-02-14 11:39 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +            SecretKeySpec sm4Key = new SecretKeySpec(key, ALGORITHM_NAME);
btw, I suppose we'd better avoid throw exception, but throw detail exception.
throws InvalidKeyException, InvalidAlgorithmParameterException, BadPaddingException, IllegalBlockSizeException...

2021-02-14 11:39 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +            sm4Cipher = sm4CipherPool.borrowObject();
这里的chiper似乎看起来用以来倒置比较合适了。 否则如果pool满了，这里就hang up了？

2021-02-14 11:39 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/pool/SM4CipherPool.java
> +    public SM4CipherPool(int init, int max) {
这个函数我们在哪儿调用了？

2021-02-14 11:39 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +            System.out.println("加密Cipher:" + cipher);
log好像不是我们应该处理的问题

2021-02-14 11:39 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +            SecretKeySpec sm4Key = new SecretKeySpec(key, ALGORITHM_NAME);
我们把具体的exception都抛出去吧。毕竟我们是基础库

2021-02-14 13:31 UTC, xiaohui249 commented on src/main/java/twgc/gm/sm4/pool/SM4CipherPool.java
> +    public SM4CipherPool(int init, int max) {
池的初始化目前我没有想到比较好的方案。目前我想到的两个方案：1. 直接在SM4Util中通过静态变量的方式内置设定好大小的池，这种方式使用不太灵活；2. 通过SM4Util的构造函数传参init和max，调用SM4CipherPool(int init, int max)来初始化一个池，这种方式对于工具类的使用不太友好。

2021-02-14 13:33 UTC, xiaohui249 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +            sm4Cipher = sm4CipherPool.borrowObject();
池的应用就是满了就会hang up，所有池大小的设置需要根据实际应用场景来设置。

2021-02-14 13:38 UTC, xiaohui249 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +            SecretKeySpec sm4Key = new SecretKeySpec(key, ALGORITHM_NAME);
sm4CipherPool.borrowObject();这里抛出的就是Exception，我们没有必要定义一个Exception再抛出去吧？

2021-02-14 13:49 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/pool/SM4CipherPool.java
> +    public SM4CipherPool(int init, int max) {
是的，所以在我们目前的这个pr里，我建议通过依赖倒置的方式来处理chiper对象和chiper pool

2021-02-14 13:49 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +            sm4Cipher = sm4CipherPool.borrowObject();
是的，所以在我们目前的这个pr里，我建议通过依赖倒置的方式来处理chiper对象和chiper pool

2021-02-14 13:52 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +            SecretKeySpec sm4Key = new SecretKeySpec(key, ALGORITHM_NAME);
我理解，我们是基础库。我们没有必要
1. 定义一个exception。
2. 用exception包括了具体的exception类型。

比如：
这里实际上底层是InvalidKeyException，但是因为我们这里函数抛出的是Exception而不是具体的InvalidKeyException，因此上层调用者无法确定到底是什么问题。（除非反射什么的。。。）
与其这样，不如我们把所有的Exception一个个的抛出去/干脆我们函数里不catch了。

2021-02-14 13:52 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +            SecretKeySpec sm4Key = new SecretKeySpec(key, ALGORITHM_NAME);
```
public byte[] encrypt(byte[] input, chiper chiper, SecretKeySpec sm4Key, SM4ModeAndPaddingEnum sm4ModeAndPaddingEnum, byte[] iv) throws InvalidKeyException, InvalidAlgorithmParameterException, BadPaddingException, IllegalBlockSizeException...
```

2021-02-15 03:26 UTC, xiaohui249 commented on src/main/java/twgc/gm/sm4/SM4Util.java
> +            SecretKeySpec sm4Key = new SecretKeySpec(key, ALGORITHM_NAME);
目前代码里本来就没有catch。当一个函数中同时有具体异常（InvalidKeyException, InvalidAlgorithmParameterException, BadPaddingException, IllegalBlockSizeException...）和非具体异常（Exception）需要抛出时，在函数定义处只能抛出Exception，其他具体异常抛出没有意义了。你可以试试

2021-02-15 03:35 UTC, xiaohui249 commented on src/main/java/twgc/gm/sm4/pool/SM4CipherPool.java
> +    public SM4CipherPool(int init, int max) {
目前cipher池是根据commons-pool的通用方式来实现的，commons-pool和池对象的依赖倒置不太明白怎么实现。

2021-02-15 07:38 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm4/pool/SM4CipherPool.java
> +    public SM4CipherPool(int init, int max) {
ok，那后边我来吧。

2021-02-15 07:39 UTC, SamYuan1990 approved these changes

2021-02-15 07:40 UTC, merged