impl for Iot pool obj
Hyperledger-TWGC/java-gm pull request #49
Opened 2021-02-15 08:50 UTC by SamYuan1990

Signed-off-by: SamYuan1990 <yy19902439@126.com>

2021-02-15 09:49 UTC, xiaohui249 requested changes

2021-02-15 09:49 UTC, xiaohui249 commented on src/test/java/SM4UtilTest.java
> +        sm4CipherPool.returnObject(sm4Cipher);
对象归还建议放到finally中，否则如果程序中间出现异常，对象无法归还，导致对象池可用对象为0，程序会hang up

2021-02-15 09:49 UTC, xiaohui249 commented on src/test/java/SM4UtilTest.java
> +        sm4CipherPool.returnObject(sm4Cipher);
其他地方类同

2021-02-15 10:41 UTC, SamYuan1990 commented on src/test/java/SM4UtilTest.java
> +        sm4CipherPool.returnObject(sm4Cipher);
updated.

2021-02-16 07:20 UTC, xiaohui249 approved these changes

2021-02-16 07:22 UTC, merged