SM3算法使用对象通用池来管理Digest对象，优化性能同时避免线程安全
Hyperledger-TWGC/java-gm pull request #50
Opened 2021-02-15 12:00 UTC by xiaohui249

Signed-off-by: Xiao Hui <xiaohui_1123@126.com>

2021-02-15 12:02 UTC, SamYuan1990 commented
sm3...也需要么？🤔

2021-02-16 03:44 UTC, xiaohui249 commented
> sm3...也需要么？🤔

SM3Digest也存在线程安全问题，所以之前的代码里你使用了类级别的synchronized来解决线程安全问题，但是这将导致同一个虚拟机启动的程序中，所有使用SM3Util进行hash或者verify都需要串行执行，这个点就类似高速公路上的一个关隘，一夫当关，影响通行效率。

2021-02-16 04:22 UTC, SamYuan1990 commented
> > sm3...也需要么？🤔
> 
> SM3Digest也存在线程安全问题，所以之前的代码里你使用了类级别的synchronized来解决线程安全问题，但是这将导致同一个虚拟机启动的程序中，所有使用SM3Util进行hash或者verify都需要串行执行，这个点就类似高速公路上的一个关隘，一夫当关，影响通行效率。

`hash`是`O(1)`的复杂度，考虑`n`个并发，最差变为`O(n)`。
然而从CPU架构等角度出发，我们做pool的开销（内存对象加载）的`I/O`是不是会大于`O(n)`?
我理解pool也是在堆上。。。是不是一个factory类就够了？ 每次从factory类里new一个对象，整段函数调用后销毁即可。（也就是用pool的意义？）这里和sm4不同的地方在于sm4那边因为`chiper`，涉及到`chiper`对象的`n *  算法`个数的大规模构建，因此复用节省开销。

2021-02-16 05:27 UTC, xiaohui249 commented
> > > sm3...也需要么？🤔
> > 
> > 
> > SM3Digest也存在线程安全问题，所以之前的代码里你使用了类级别的synchronized来解决线程安全问题，但是这将导致同一个虚拟机启动的程序中，所有使用SM3Util进行hash或者verify都需要串行执行，这个点就类似高速公路上的一个关隘，一夫当关，影响通行效率。
> 
> `hash`是`O(1)`的复杂度，考虑`n`个并发，最差变为`O(n)`。
> 然而从CPU架构等角度出发，我们做pool的开销（内存对象加载）的`I/O`是不是会大于`O(n)`?
> 我理解pool也是在堆上。。。是不是一个factory类就够了？ 每次从factory类里new一个对象，整段函数调用后销毁即可。（也就是用pool的意义？）这里和sm4不同的地方在于sm4那边因为`chiper`，涉及到`chiper`对象的`n * 算法`个数的大规模构建，因此复用节省开销。

1. SM3哈希算法的时间复杂度与哈希对象的大小有关，不是O(1)的复杂度，空间复杂度也不是O(1)。
2. 如果整个应用程序加载初始化全局静态的SM3Digest pool（至于池的大小需要使用者设定合适的值，如果设置不当，是程序员经验问题，而不是程序设计的问题），可以避免频繁创建SM3Digest对象，无论是内存的开销还是时间的开销都要小一些，这跟SM3Digest的具体算法无关，只关于SM3Digest这个对象创建的内存开销和时间开销。退了一步讲，用内存换取性能是值得的。
3. 关于SM4的使用，正常使用的情况下，一般也不会一次性初始化全部模式的Cipher对象，也是用哪个模式就初始哪个模式的Cipher对象，之后就销毁了，就像最开始SM4Util工具类提供的静态方法，之所以进行重构，就是因为每次调用静态方法时new某个模式的Cipher对象比较耗时。

2021-02-16 05:34 UTC, SamYuan1990 requested changes

2021-02-16 05:34 UTC, SamYuan1990 commented on src/test/java/SM3UtilTest.java
> +            sm3Digest.reset();
这个reset 如果需要是不是可以放到pool的returnobj方法里？

2021-02-16 05:34 UTC, SamYuan1990 commented on src/test/java/SM3UtilThreadTest.java
> +                } catch (Exception e) {
这里直接打印真的好么？要不要收集一下？

2021-02-16 05:34 UTC, SamYuan1990 commented on src/test/java/SM3UtilThreadTest.java
> +        sm3DigestPool.returnObject(sm3Digest);
这里finally

2021-02-16 05:34 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm3/pool/SM3DigestPool.java
> +           obj.reset();
既然这里已经reset了。。。

2021-02-16 05:34 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm3/SM3Util.java
> +        digest.update(srcData, 0, srcData.length);
同理，就算有pool和注入，这里依旧需要用snychronized关键字。
假设永远用一个`digest`对象，那么这里还是会有安全问题。
因为我们的pool在get obj之前没有校验。

2021-02-16 06:09 UTC, xiaohui249 commented on src/test/java/SM3UtilTest.java
> +            sm3Digest.reset();
return方法里面有处理

2021-02-16 06:10 UTC, xiaohui249 commented on src/main/java/twgc/gm/sm3/SM3Util.java
> +        digest.update(srcData, 0, srcData.length);
不会，每次归还的时候reset()了，已经通过并发测试了

2021-02-16 06:17 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm3/SM3Util.java
> +        digest.update(srcData, 0, srcData.length);
通过测试是因为
```
 SM3Digest sm3DigestInThead = null;
                try {
                    sm3DigestInThead = sm3DigestPool.borrowObject();
                    results.add(SM3Util.verify(sm3DigestInThead, message, hashVal));
                } catch (Exception e) {
```
这里的并发不够。
common pool的borrow obj本身不能保证两个thread一定拿到不同的obj。也无法保证obj本身的状态。
因此pool的borrow存在borrow on test这个方式。

2021-02-16 06:18 UTC, xiaohui249 commented on src/test/java/SM3UtilThreadTest.java
> +                } catch (Exception e) {
异常的处理跟业务相关，个人觉得咱们测试案例里面的异常这样子处理就可以了，已经达到了并行测试的目的。基础库的调用者可以根据实际使用情况对异常进行对应的处理。

2021-02-16 06:20 UTC, SamYuan1990 commented on src/test/java/SM3UtilTest.java
> +            sm3Digest.reset();
那这里应该删除，下同。

2021-02-16 06:22 UTC, xiaohui249 commented on src/test/java/SM3UtilTest.java
> +            sm3Digest.reset();
这里通过reset之后直接复用了同一个从池里获得的Digest对象，非并发环境可以这么使用。

2021-02-16 06:30 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm3/SM3Util.java
> +        digest.update(srcData, 0, srcData.length);
ok

2021-02-16 06:32 UTC, SamYuan1990 commented on src/test/java/SM3UtilThreadTest.java
> +                } catch (Exception e) {
```
                } catch (Exception e) {
                    ex.add(e);
                } finally {
                    if (sm4Ciphertest != null) {
                        sm4CipherPool.returnObject(sm4Ciphertest);
                    }
                }
            }).start();
        }
        Thread.sleep(5000);
        while (!ex.isEmpty()) {
            Exception e =  ex.poll();
            e.printStackTrace();
            Assert.fail(exceptionHappened);
        }
```
从测试的角度，我在sm4那边是统一在外边处理的，都可以。

2021-02-16 06:37 UTC, SamYuan1990 commented on src/test/java/SM3UtilTest.java
> +            sm3Digest.reset();
总觉得。。。怪怪的。。。
https://github.com/Hyperledger-TWGC/java-gm/pull/50/files/87228ea801b4cdd6923fa9f5941bbad32bbe2d31#diff-290252eef6355b099532429ccdf9cd9fbaa7aac1914759b1cb0bd0431a6e319bL18
之前我们没reset也能用。。。

2021-02-16 07:07 UTC, xiaohui249 commented on src/test/java/SM3UtilTest.java
> +            sm3Digest.reset();
digest的doFinal中执行了reset了，这里已经删除。

2021-02-16 07:08 UTC, xiaohui249 commented on src/test/java/SM3UtilTest.java
> +            sm3Digest.reset();
digest对象的doFinal中已经执行了reset方法，已经删除了sm3Digest.reset();

2021-02-16 07:09 UTC, xiaohui249 commented on src/test/java/SM3UtilThreadTest.java
> +                } catch (Exception e) {
异常已经实现收集，与sm4相同

2021-02-16 07:18 UTC, xiaohui249 commented on src/test/java/SM3UtilThreadTest.java
> +        sm3DigestPool.returnObject(sm3Digest);
updated

2021-02-16 07:34 UTC, SamYuan1990 approved these changes

2021-02-16 07:34 UTC, merged