增加cert模块，支持颁发SM2证书
Hyperledger-TWGC/java-gm pull request #55
Opened 2021-04-16 10:14 UTC by EdgarLQS

1、增加cert模块，支持颁发SM2证书，测试见SM2UtilTest
 2、SM2UtilTest增加静态代码块，避免运行 generateFile() 后再次运行报错

2021-04-17 03:35 UTC, davidkhala commented on src/main/java/twgc/gm/cert/CertSNAllocator.java
> +public interface CertSNAllocator {
这个接口是定义一个随机数生成器么？

2021-04-17 03:39 UTC, davidkhala commented on src/main/java/twgc/gm/cert/SM2X509CertMaker.java
> +     *                      这里仅是为了演示BC库签发证书的用法，所以暂时不作太多要求。
提及了未知的BC库

2021-04-17 03:39 UTC, davidkhala commented on src/main/java/twgc/gm/cert/SM2X509CertMaker.java
> +     * @throws Exception 如果错误发生
多余的 `@throws`

2021-04-17 03:41 UTC, davidkhala commented on src/test/java/SM2UtilTest.java
> +    // 静态代码块，避免运行 generateFile() 后再次运行报错
这个是为什么？之前不是已经运行过类似的一次了么？

2021-04-22 13:38 UTC, EdgarLQS commented on src/main/java/twgc/gm/cert/CertSNAllocator.java
> +public interface CertSNAllocator {
对  我的理解是每一个颁发的证书都是具有唯一向前的随机数进行标记

2021-04-22 13:38 UTC, EdgarLQS commented on src/main/java/twgc/gm/cert/SM2X509CertMaker.java
> +     *                      这里仅是为了演示BC库签发证书的用法，所以暂时不作太多要求。
这段只是解释，已删除

2021-04-22 13:38 UTC, EdgarLQS commented on src/main/java/twgc/gm/cert/SM2X509CertMaker.java
> +     * @throws Exception 如果错误发生
收到，已处理

2021-04-22 13:38 UTC, EdgarLQS commented on src/test/java/SM2UtilTest.java
> +    // 静态代码块，避免运行 generateFile() 后再次运行报错
如果不加这段代码，当程序运行后（即在本地保存了私钥、公钥后），再次运行时会发生载入公钥错误，错误如下
java.security.NoSuchProviderException: no such provider: BC

2021-04-30 14:19 UTC, SamYuan1990 requested changes

2021-04-30 14:19 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm2/SM2Util.java
> +        try {
不要try， final，直接抛出

2021-04-30 14:19 UTC, SamYuan1990 commented on src/main/java/twgc/gm/cert/SM2X509CertMaker.java
> +    private X509v3CertificateBuilder genX509v3CertificateBuilder(CertLevel certLevel, PKCS10CertificationRequest request) throws Exception {
同makeContentSignerBuilder

2021-04-30 14:19 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +            Assert.assertEquals("SM3WITHSM2", this.x509Certificate.getSigAlgName());
const

2021-04-30 14:19 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +        long certExpire = 20L * 365 * 24 * 60 * 60 * 1000;
？为什么不提出去作为参数呢？

2021-04-30 14:19 UTC, SamYuan1990 commented on src/main/java/twgc/gm/cert/SM2X509CertMaker.java
> +                if (BCStyle.CN.equals(type)) {
这里只处理CN这个常量的背景是什么？

2021-04-30 14:19 UTC, SamYuan1990 commented on src/main/java/twgc/gm/cert/SM2X509CertMaker.java
> +    private X509v3CertificateBuilder genX509v3CertificateBuilder(CertLevel certLevel, PKCS10CertificationRequest request) throws Exception {
另外建议X500Name 通过依赖倒置作为参数传入，不在这里处理。我们可以提供一个参考实现/基于某标准的参考实现函数来构造500Name而非写死。

2021-04-30 14:19 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +    // 静态代码块，避免运行 generateFile() 后再次运行报错
https://github.com/Hyperledger-TWGC/java-gm/blob/master/src/main/java/twgc/gm/sm2/SM2Util.java#L62
在类加载中使用这个方法？

建议打印错误栈追一下这个问题。
参考
https://github.com/Hyperledger-TWGC/java-gm/blob/master/src/main/java/twgc/gm/sm2/SM2Util.java#L203
我们在同样的逻辑下调用加载私钥的函数中也加载了bc库的样子。

2021-04-30 14:20 UTC, SamYuan1990 commented
DCO检测

2021-06-29 14:21 UTC, closed without merging