SM2Util optimization
Hyperledger-TWGC/java-gm pull request #58
Opened 2021-06-12 23:51 UTC by xiaohui249

1.使用单例模式生成SecureRandom对象，节约对象频繁创建消耗的资源；
2.使用对象池方式解决SM2Engine线程不安全问题，替换原先的synchronized方式，并发加密情况下，性能有显著提升。

Signed-off-by: Xiao Hui <xiaohui_1123@126.com>

2021-06-13 03:00 UTC, davidkhala commented
LGTM and wait for @SamYuan1990

2021-06-13 03:01 UTC, davidkhala approved these changes

2021-06-14 06:54 UTC, SamYuan1990 requested changes

2021-06-14 06:54 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm2/SecureRandomFactory.java
> +    private static class CachedSecureRandomHolder {
cached?

what's in cache?

2021-06-14 06:54 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm2/pool/SM2EngineFactory.java
> +    public SM2Engine create() throws Exception {
we need keep supports for both C1C3C2 and C1C2C3.

2021-06-14 06:54 UTC, SamYuan1990 commented on src/main/java/twgc/gm/sm2/SM2Util.java
>      public byte[] sign(PrivateKey privateKey, byte[] message) throws SignatureException, InvalidKeyException {
if we get securrandom() in from any factory, why not 
```
    public byte[] sign(PrivateKey privateKey, byte[] message,random SecureRandom()) throws SignatureException, InvalidKeyException {
```
??

2021-06-14 06:54 UTC, SamYuan1990 commented on src/test/java/SM2UtilTest.java
> +            SM2Engine sm2Engine = new SM2Engine(SM2Engine.Mode.C1C3C2);
as we have SM2EngineFactory,` SM2Engine sm2Engine` should get from factory.(类构成方法在测试中建议和用户使用保持一致性)

2021-06-14 06:54 UTC, SamYuan1990 commented on src/test/java/SM2UtilThreadTest.java
> +            System.out.println("cost times :" + (end - start));
这里的时间不代表测试成功。这行打印应该放后边所有校验结束之后。

2021-06-14 06:54 UTC, SamYuan1990 commented on src/test/java/SM2UtilThreadTest.java
> +            System.out.println("cost times :" + (end - start));
另外。。。在思考如果是打印时间，也许用时间库比较舒服？

2021-06-14 06:54 UTC, SamYuan1990 commented on src/test/java/SM2UtilThreadTest.java
> +            SM2Engine sm2Engine = sm2EnginePool.borrowObject();
这里的测试改动我有一个疑问：
旧的代码中
`synchronized` 和`new sm2Engine()`关键字保证了所有的测试都测试在同一个`sm2Engine`对象上。

现在新的改动
感觉上是在测试factory啊。
是否能够避免两个thread borrow到了同一个`sm2Engine()`实例的时候的并发问题？

我的理解现在这段代码
由于实现时候还是对于某个engine对象来操作的加解密。
因此并没有测试到某个对象的并发安全。而是测试了整个factory的并发安全。当然从实际添加factory类的这个角度，factory本身的多线程安全我们能够覆盖到也是好事情。

2021-06-14 06:54 UTC, SamYuan1990 commented on src/test/java/SM2UtilThreadTest.java
> +            SM2Engine sm2Engine = sm2EnginePool.borrowObject();
CC: @davidkhala , 麻烦double check

2021-06-14 07:20 UTC, xiaohui249 commented on src/main/java/twgc/gm/sm2/SecureRandomFactory.java
> +    private static class CachedSecureRandomHolder {
我理解单例模式类似cache了一个类实例，这里当然是SecureRandom的实例，无论在哪里都可以快速返回一个已经存在的实例对象。由于jdk中的JCAUtil不推荐使用了，所以这里创建了一个类来做这件事。

2021-06-14 07:27 UTC, xiaohui249 commented on src/main/java/twgc/gm/sm2/pool/SM2EngineFactory.java
> +    public SM2Engine create() throws Exception {
No problem！SM2Util的加密和解密方法签名多加了一个SM2Engine类型参数，是可以实现C1C3C2和C1C2C3模式的。但要在多线程环境下，还需要增加支持C1C2C3模式对象池。

2021-06-14 07:32 UTC, xiaohui249 commented on src/main/java/twgc/gm/sm2/SM2Util.java
>      public byte[] sign(PrivateKey privateKey, byte[] message) throws SignatureException, InvalidKeyException {
sign和verify我还没有验证它们的线程安全问题，如果验证之后有问题，我会再进行调整。针对上述的问题，我认为公共API暴露的参数尽可能少比较好，用户使用体验会更好一些。比如：sign中的SecureRandom对象，如果API代码能够内部获取到，就不需要用户调用时传入。

2021-06-14 07:34 UTC, xiaohui249 commented on src/test/java/SM2UtilTest.java
> +            SM2Engine sm2Engine = new SM2Engine(SM2Engine.Mode.C1C3C2);
嗯嗯，之前我理解没有要求一定要支持C1C2C3模式，所以就只考虑将C1C3C2模式对象池化，后续可以补充

2021-06-14 07:38 UTC, xiaohui249 commented on src/test/java/SM2UtilThreadTest.java
> +            System.out.println("cost times :" + (end - start));
这里表示所有线程都跑完了，这是时间主要是测试性能的。通过调整线程数和SM2EnginePool对象池大小来测试性能，当设置对象池为1时，相当于原来的sychronized的方案，所有线程处理完的耗时明显要大一些。

2021-06-14 07:46 UTC, xiaohui249 commented on src/test/java/SM2UtilThreadTest.java
> +            SM2Engine sm2Engine = sm2EnginePool.borrowObject();
1. SM2Util的加密和解密方法加synchronized的原因是因为SM2Engine对象不是线程安全的。我在原来的代码上注释了synchronized之后，跑多线程测试，结果报错异常。单独给sm2Engine.processBlock(message, 0, message.length)这行加上synchronized之后再测试，结果正常了。
2. 在并发环境中使用synchronized，加密解密方法效率收到明显影响。这个可以通过调整SM2EnginePool对象的池大小进行测试。
综合上述问题，本次提交代码解决的问题是：通过池化SM2Engine对象实现线程安全与加解密方法性能的平衡状态。

2021-06-14 07:56 UTC, xiaohui249 commented
综合 @SamYuan1990 的所有评论来看，本次提交没有考虑SM2EnginePool支持C1C2C3模式，下个PR将参考SM4Cipher的封装方式进行完善。

2021-06-15 01:10 UTC, xiaohui249 commented on src/test/java/SM2UtilThreadTest.java
> +            SM2Engine sm2Engine = sm2EnginePool.borrowObject();
"是否能够避免两个thread borrow到了同一个sm2Engine()实例的时候的并发问题？",对象没有归还到对象池之前，是不可能被borrow出去的，不会出现两个线程同时操作同一个对象，这是通过对象池解决对象线程安全问题的原理。

2021-06-23 03:04 UTC, SamYuan1990 approved these changes

2021-06-23 03:05 UTC, merged