Impl for pool created from property file
Hyperledger-TWGC/java-gm pull request #67
Opened 2021-08-28 06:59 UTC by SamYuan1990

1. 重构了一下，把pool单独作为一个package.
1. 添加了pool对于配置文件的读取和支持.
1. 保留了手工创建config和pool的功能.
1. 在readme中添加了对于pool设计的思路.

2021-08-28 07:02 UTC, SamYuan1990 commented
@davidkhala , @xiaohui249 我在思考这个pr merge之后我们要不要发一个release出来？

2021-09-01 07:08 UTC, davidkhala commented on src/main/java/twgc/gm/pool/SM2PoolConfig.java
> +            InputStream in = this.getClass().getResourceAsStream(file);
`InputStream in = this.getClass().getResourceAsStream(file);` 这一段有非抛出型替代方案么？我看只是一个读文件
如果确定要throw，在这里可以不catch直接扔出去么？

2021-09-01 07:09 UTC, davidkhala reviewed
LGTM but some discussion on file reader lines

2021-09-02 05:56 UTC, xiaohui249 requested changes

2021-09-02 05:56 UTC, xiaohui249 commented on src/main/java/twgc/gm/pool/SM2PoolConfig.java
> +            InputStream in = this.getClass().getResourceAsStream(file);
可以试试try-finally，最后需要关闭InputStream对象

2021-09-02 05:56 UTC, xiaohui249 commented on src/main/java/twgc/gm/pool/SM4PoolConfig.java
> +    public void loadConfig(String file) {
loadConfig这个方法在每个PoolConfig类中都出现了，能否考虑抽取出来形成公共方法？

2021-09-04 07:30 UTC, SamYuan1990 commented on src/main/java/twgc/gm/pool/SM2PoolConfig.java
> +            InputStream in = this.getClass().getResourceAsStream(file);
考虑到用户自己提供文件的可能用法，这里最后还是把这个异常直接扔出去了。

2021-09-04 07:30 UTC, SamYuan1990 commented on src/main/java/twgc/gm/pool/SM4PoolConfig.java
> +    public void loadConfig(String file) {
暂时放在const里边了。

2021-09-04 07:32 UTC, SamYuan1990 commented
最新的commit修改了几点
1. config类通过Properties类构建。
2. 一个通用的load Properties的方法。
3. 考虑到使用者提供文件目录的情况，不在内部catch异常。

2021-09-04 07:37 UTC, SamYuan1990 commented
sm4 provider check的在类加载中的判断位置。

2021-09-10 10:29 UTC, xiaohui249 approved these changes
LGTM

2021-09-13 06:24 UTC, merged