解决连接池配置文件加载失效的问题
Hyperledger-TWGC/java-gm pull request #69
Opened 2021-09-25 15:38 UTC by xiaohui249

2021-09-27 02:26 UTC, davidkhala commented
@xiaohui249 肖总，commit tree看起来出了问题，里面夹杂了之前的提交，看似是在本地分支上使用了merge而不是rebase的缘故。可以重新整理一下之后再force push么？

2021-09-27 10:01 UTC, SamYuan1990 requested changes
General speaking it is looks good to me, but you need to use rebase instead of merge to sync with latest main branch.

2021-09-27 10:02 UTC, SamYuan1990 commented on src/test/java/SM2UtilThreadTest.java
> +            System.out.println("maxTotal=" + sm2EnginePool.getMaxTotal() + ", maxIdle=" + sm2EnginePool.getMaxIdle() + ", minIdle=" + sm2EnginePool.getMinIdle());
我觉得这里还是用test case来代替吧。不要用log了。

2021-09-27 10:03 UTC, SamYuan1990 commented on src/test/java/SM2UtilThreadTest.java
> +            System.out.println("maxTotal=" + sm2EnginePool.getMaxTotal() + ", maxIdle=" + sm2EnginePool.getMaxIdle() + ", minIdle=" + sm2EnginePool.getMinIdle());
比如 sm3DigestPool.getMaxTotal()

2021-09-28 13:37 UTC, xiaohui249 commented on src/test/java/SM2UtilThreadTest.java
> +            System.out.println("maxTotal=" + sm2EnginePool.getMaxTotal() + ", maxIdle=" + sm2EnginePool.getMaxIdle() + ", minIdle=" + sm2EnginePool.getMinIdle());
> 我觉得这里还是用test case来代替吧。不要用log了。

这里直接删掉吧，主要是测试配置是否生效用的。成功之后，其实已经没啥意义了。

2021-09-28 13:48 UTC, SamYuan1990 commented on src/test/java/SM2UtilThreadTest.java
> +            System.out.println("maxTotal=" + sm2EnginePool.getMaxTotal() + ", maxIdle=" + sm2EnginePool.getMaxIdle() + ", minIdle=" + sm2EnginePool.getMinIdle());
嗯，这里直接删掉。
然后可以在test case里写
assert(8,sm2EnginePool.getMaxTotal())
这样子

2021-09-28 14:03 UTC, closed without merging